title: pytri
email: jordan.matelsky@jhuapl.edu
description: >
  Pytri is a Python widget to enable substrate visualizations in a Jupyter notebook.
baseurl: "/pytri" # the subpath of your site, e.g. /blog
url: "https://iscoe.github.io/"

# Build settings
markdown: kramdown
# theme: minima
